function d_fk_drho = autoFunc_d_fk_drho(in1,lc,in3)
%AUTOFUNC_D_FK_DRHO
%    D_FK_DRHO = AUTOFUNC_D_FK_DRHO(IN1,LC,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    08-Feb-2022 22:07:24

t1 = in1(1,:);
t2 = in1(2,:);
t3 = in1(3,:);
t5 = t2+t3;
t6 = cos(t5);
d_fk_drho = [-sin(t5);t6.*sin(t1);-t6.*cos(t1)];
