function d_fk_ddrho = autoFunc_d_fk_ddrho(in1,lc,in3)
%autoFunc_d_fk_ddrho
%    D_FK_DDRHO = autoFunc_d_fk_ddrho(IN1,LC,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    30-Apr-2022 21:21:10

d_fk_ddrho = [0.0;0.0;0.0];
