function fk_hip_pos = autoFunc_fk_hip_pos(in1,lc,in3)
%autoFunc_fk_hip_pos
%    FK_HIP_POS = autoFunc_fk_hip_pos(IN1,LC,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    30-Apr-2022 21:21:10

d = in3(3,:);
ox = in3(1,:);
oy = in3(2,:);
t1 = in1(1,:);
fk_hip_pos = [ox;oy+(d.*cos(t1))./2.0;(d.*sin(t1))./2.0];
