function d_fk_ddrho = autoFunc_d_fk_ddrho(in1,lc,in3)
%AUTOFUNC_D_FK_DDRHO
%    D_FK_DDRHO = AUTOFUNC_D_FK_DDRHO(IN1,LC,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    24-Feb-2022 11:42:23

d_fk_ddrho = [0.0;0.0;0.0];
