function fk_thigh_rot = autoFunc_fk_thigh_rot(in1,lc,in3)
%AUTOFUNC_FK_THIGH_ROT
%    FK_THIGH_ROT = AUTOFUNC_FK_THIGH_ROT(IN1,LC,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    17-Feb-2022 17:00:22

t1 = in1(1,:);
t2 = in1(2,:);
t4 = cos(t1);
t5 = cos(t2);
t6 = sin(t1);
t7 = sin(t2);
fk_thigh_rot = reshape([t5,t6.*t7,-t4.*t7,0.0,t4,t6,t7,-t5.*t6,t4.*t5],[3,3]);
