function fk_hip_pos = autoFunc_fk_hip_pos(in1,lc,in3)
%AUTOFUNC_FK_HIP_POS
%    FK_HIP_POS = AUTOFUNC_FK_HIP_POS(IN1,LC,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    12-Oct-2021 02:34:18

d = in3(3,:);
ox = in3(1,:);
oy = in3(2,:);
t1 = in1(1,:);
fk_hip_pos = [ox;oy+(d.*cos(t1))./2.0;(d.*sin(t1))./2.0];
