function fk_hip_rot = autoFunc_fk_hip_rot(in1,lc,in3)
%AUTOFUNC_FK_HIP_ROT
%    FK_HIP_ROT = AUTOFUNC_FK_HIP_ROT(IN1,LC,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    03-Oct-2021 23:44:17

t1 = in1(1,:);
t3 = cos(t1);
t4 = sin(t1);
fk_hip_rot = reshape([1.0,0.0,0.0,0.0,t3,t4,0.0,-t4,t3],[3,3]);
