matlab2tikz('test.tex',...
            'extraAxisOptions',{'ylabel near ticks','xlabel near ticks',...
            'xtick={0,0.05,0.1}',...
            'scaled ticks=false',...
%             'ytick distance=0.5',...
%             'minor tick num=1',...
%             'ylabel style={font=\small\fontfamily{ptm}\selectfont}',...
%             'xlabel style={font=\small\fontfamily{ptm}\selectfont}',...
%             'legend style={font=\small\fontfamily{ptm}\selectfont},',...
%             'ticklabel style={font=\small\fontfamily{ptm}\selectfont}',...
            })