//
// Academic License - for use in teaching, academic research, and meeting
// course requirements at degree granting institutions only.  Not for
// government, commercial, or other organizational use.
// File: autoFunc_dJ_dpho.cpp
//
// MATLAB Coder version            : 5.1
// C/C++ source code generated on  : 10-Aug-2021 14:50:52
//

// Include Files
#include "autoFunc_dJ_dpho.h"
#include <cmath>

// Function Definitions
//
// AUTOFUNC_DJ_DPHO
//     DJ_DPHO = AUTOFUNC_DJ_DPHO(IN1,IN2,IN3)
// Arguments    : const double in1[3]
//                const double in2[3]
//                const double in3[5]
//                double dJ_dpho[27]
// Return Type  : void
//
void autoFunc_dJ_dpho(const double in1[3], const double [3], const double [5],
                      double dJ_dpho[27])
{
  double t11;
  double t12;
  double t13;
  double t2;
  double t3;
  double t4;
  double t5;
  double t9;

  //     This function was generated by the Symbolic Math Toolbox version 8.6.
  //     10-Aug-2021 14:48:22
  t2 = std::cos(in1[0]);
  t3 = std::sin(in1[0]);
  t4 = in1[1] + in1[2];
  t5 = std::cos(t4);
  t4 = std::sin(t4);
  t9 = t3 * t5;
  t11 = t3 * t4;
  t12 = -(t2 * t5);
  t13 = t2 * -t4;
  dJ_dpho[0] = 0.0;
  dJ_dpho[1] = t2 * t4;
  dJ_dpho[2] = t11;
  dJ_dpho[3] = -t4;
  dJ_dpho[4] = t9;
  dJ_dpho[5] = t12;
  dJ_dpho[6] = -t4;
  dJ_dpho[7] = t9;
  dJ_dpho[8] = t12;
  dJ_dpho[9] = 0.0;
  dJ_dpho[10] = -t3;
  dJ_dpho[11] = t2;
  dJ_dpho[12] = 0.0;
  dJ_dpho[13] = 0.0;
  dJ_dpho[14] = 0.0;
  dJ_dpho[15] = 0.0;
  dJ_dpho[16] = 0.0;
  dJ_dpho[17] = 0.0;
  dJ_dpho[18] = 0.0;
  dJ_dpho[19] = t12;
  dJ_dpho[20] = -t9;
  dJ_dpho[21] = t5;
  dJ_dpho[22] = t11;
  dJ_dpho[23] = t13;
  dJ_dpho[24] = t5;
  dJ_dpho[25] = t11;
  dJ_dpho[26] = t13;
}

//
// File trailer for autoFunc_dJ_dpho.cpp
//
// [EOF]
//
