//
// Academic License - for use in teaching, academic research, and meeting
// course requirements at degree granting institutions only.  Not for
// government, commercial, or other organizational use.
// File: autoFunc_d_fk_dc.cpp
//
// MATLAB Coder version            : 5.1
// C/C++ source code generated on  : 10-Aug-2021 14:50:52
//

// Include Files
#include "autoFunc_d_fk_dc.h"
#include <cmath>

// Function Definitions
//
// AUTOFUNC_D_FK_DC
//     D_FK_DC = AUTOFUNC_D_FK_DC(IN1,IN2,IN3)
// Arguments    : const double in1[3]
//                const double in2[3]
//                const double in3[5]
//                double d_fk_dc[9]
// Return Type  : void
//
void autoFunc_d_fk_dc(const double in1[3], const double [3], const double [5],
                      double d_fk_dc[9])
{
  double t2;
  double t3;
  double t4;
  double t5;

  //     This function was generated by the Symbolic Math Toolbox version 8.6.
  //     10-Aug-2021 14:48:21
  t2 = std::cos(in1[0]);
  t3 = std::sin(in1[0]);
  t4 = in1[1] + in1[2];
  t5 = std::cos(t4);
  t4 = std::sin(t4);
  d_fk_dc[0] = t5;
  d_fk_dc[1] = t3 * t4;
  d_fk_dc[2] = -t2 * t4;
  d_fk_dc[3] = 0.0;
  d_fk_dc[4] = t2;
  d_fk_dc[5] = t3;
  d_fk_dc[6] = t4;
  d_fk_dc[7] = -t3 * t5;
  d_fk_dc[8] = t2 * t5;
}

//
// File trailer for autoFunc_d_fk_dc.cpp
//
// [EOF]
//
