//
// Academic License - for use in teaching, academic research, and meeting
// course requirements at degree granting institutions only.  Not for
// government, commercial, or other organizational use.
// File: autoFunc_dJ_dq.cpp
//
// MATLAB Coder version            : 5.1
// C/C++ source code generated on  : 10-Aug-2021 14:50:52
//

// Include Files
#include "autoFunc_dJ_dq.h"
#include <cmath>

// Function Definitions
//
// AUTOFUNC_DJ_DQ
//     DJ_DQ = AUTOFUNC_DJ_DQ(IN1,IN2,IN3)
// Arguments    : const double in1[3]
//                const double in2[3]
//                const double in3[5]
//                double dJ_dq[27]
// Return Type  : void
//
void autoFunc_dJ_dq(const double in1[3], const double in2[3], const double in3[5],
                    double dJ_dq[27])
{
  double t10;
  double t13;
  double t17;
  double t18;
  double t2;
  double t26;
  double t27;
  double t28;
  double t3;
  double t31;
  double t34;
  double t34_tmp;
  double t35;
  double t4;
  double t5;
  double t6;
  double t7;
  double t8;
  double t9;

  //     This function was generated by the Symbolic Math Toolbox version 8.6.
  //     10-Aug-2021 14:48:21
  t2 = std::cos(in1[0]);
  t3 = std::cos(in1[1]);
  t4 = std::cos(in1[2]);
  t5 = std::sin(in1[0]);
  t6 = std::sin(in1[1]);
  t7 = std::sin(in1[2]);
  t8 = in1[1] + in1[2];
  t9 = std::cos(t8);
  t10 = t3 * in3[3];
  t8 = std::sin(t8);
  t13 = in2[0] * t9;
  t17 = in2[2] * t8;
  t18 = in3[4] * t8;
  t9 = (in3[4] * t9 + in2[0] * t8) + -(in2[2] * t9);
  t8 = (t13 + t17) + -t18;
  t26 = (t18 + -t13) + -t17;
  t27 = t5 * t8;
  t28 = t2 * t9;
  t18 = t2 * t8;
  t31 = t10 + t9;
  t34_tmp = t6 * in3[3] + t26;
  t34 = -t2 * t34_tmp;
  t35 = -t5 * t34_tmp;
  t8 = -(t5 * t9);
  dJ_dq[0] = 0.0;
  dJ_dq[1] = (((((((-in2[1] * t2 - in3[2] * t2) - t5 * t10) - in2[0] * t3 * t5 *
                  t7) - in2[0] * t4 * t5 * t6) + in2[2] * t3 * t4 * t5) - in2[2]
               * t5 * t6 * t7) - in3[4] * t3 * t4 * t5) + in3[4] * t5 * t6 * t7;
  t9 = in2[0] * t2;
  t13 = in2[2] * t2;
  t17 = in3[4] * t2;
  dJ_dq[2] = (((((((-in2[1] * t5 - in3[2] * t5) + t2 * t10) + t9 * t3 * t7) + t9
                 * t4 * t6) - t13 * t3 * t4) + t13 * t6 * t7) + t17 * t3 * t4) -
    t17 * t6 * t7;
  dJ_dq[3] = 0.0;
  dJ_dq[4] = t34;
  dJ_dq[5] = t35;
  dJ_dq[6] = 0.0;
  dJ_dq[7] = t18;
  dJ_dq[8] = t27;
  dJ_dq[9] = 0.0;
  dJ_dq[10] = t34;
  dJ_dq[11] = t35;
  dJ_dq[12] = t34_tmp;
  dJ_dq[13] = -t5 * t31;
  dJ_dq[14] = t2 * t31;
  dJ_dq[15] = t26;
  dJ_dq[16] = t8;
  dJ_dq[17] = t28;
  dJ_dq[18] = 0.0;
  dJ_dq[19] = t18;
  dJ_dq[20] = t27;
  dJ_dq[21] = t26;
  dJ_dq[22] = t8;
  dJ_dq[23] = t28;
  dJ_dq[24] = t26;
  dJ_dq[25] = t8;
  dJ_dq[26] = t28;
}

//
// File trailer for autoFunc_dJ_dq.cpp
//
// [EOF]
//
