function jacobian = autoFunc_d_fk_dq(in1,in2,in3)
%AUTOFUNC_D_FK_DQ
%    JACOBIAN = AUTOFUNC_D_FK_DQ(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    01-Sep-2021 23:06:51

cx = in2(1,:);
cy = in2(2,:);
cz = in2(3,:);
d = in3(3,:);
ll = in3(5,:);
q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
ul = in3(4,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q3);
t5 = sin(q1);
t6 = sin(q2);
t7 = sin(q3);
t8 = q2+q3;
t9 = cos(t8);
t10 = sin(t8);
t11 = t6.*ul;
t12 = cx.*t9;
t13 = cz.*t9;
t14 = ll.*t9;
t15 = cx.*t10;
t16 = cz.*t10;
t17 = ll.*t10;
t18 = -t11;
t19 = -t14;
t20 = -t15;
t21 = -t17;
t22 = t12+t16+t21;
t23 = t18+t22;
jacobian = reshape([0.0,-cy.*t5-d.*t5+t2.*t3.*ul+cx.*t2.*t3.*t7+cx.*t2.*t4.*t6-cz.*t2.*t3.*t4+cz.*t2.*t6.*t7+ll.*t2.*t3.*t4-ll.*t2.*t6.*t7,cy.*t2+d.*t2+t3.*t5.*ul+cx.*t3.*t5.*t7+cx.*t4.*t5.*t6-cz.*t3.*t4.*t5+cz.*t5.*t6.*t7+ll.*t3.*t4.*t5-ll.*t5.*t6.*t7,t13+t19+t20-t3.*ul,-t5.*(t11-t12-t16+t17),t2.*(t11-t12-t16+t17),t13+t19+t20,t5.*t22,-t2.*t22],[3,3]);
