function dJ_dq = autoFunc_dJ_dq(in1,in2,in3)
%AUTOFUNC_DJ_DQ
%    DJ_DQ = AUTOFUNC_DJ_DQ(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    01-Sep-2021 23:06:51

cx = in2(1,:);
cy = in2(2,:);
cz = in2(3,:);
d = in3(3,:);
ll = in3(5,:);
q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
ul = in3(4,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q3);
t5 = sin(q1);
t6 = sin(q2);
t7 = sin(q3);
t8 = q2+q3;
t9 = cos(t8);
t10 = t3.*ul;
t11 = sin(t8);
t12 = t6.*ul;
t13 = cx.*t9;
t14 = cz.*t9;
t15 = ll.*t9;
t16 = cx.*t11;
t17 = cz.*t11;
t18 = ll.*t11;
t19 = -t12;
t20 = -t13;
t21 = -t14;
t22 = -t17;
t23 = -t18;
t24 = t15+t16+t21;
t25 = t13+t17+t23;
t26 = t18+t20+t22;
t27 = t5.*t25;
t28 = t2.*t24;
t29 = t2.*t25;
t30 = t5.*t24;
t31 = t10+t24;
t33 = t19+t25;
t34 = -t2.*(t12+t26);
t35 = -t5.*(t12+t26);
t32 = -t30;
dJ_dq = reshape([0.0,-cy.*t2-d.*t2-t5.*t10-cx.*t3.*t5.*t7-cx.*t4.*t5.*t6+cz.*t3.*t4.*t5-cz.*t5.*t6.*t7-ll.*t3.*t4.*t5+ll.*t5.*t6.*t7,-cy.*t5-d.*t5+t2.*t10+cx.*t2.*t3.*t7+cx.*t2.*t4.*t6-cz.*t2.*t3.*t4+cz.*t2.*t6.*t7+ll.*t2.*t3.*t4-ll.*t2.*t6.*t7,0.0,t34,t35,0.0,t29,t27,0.0,t34,t35,t12+t26,-t5.*t31,t2.*t31,t26,t32,t28,0.0,t29,t27,t26,t32,t28,t26,t32,t28],[9,3]);
