function dJ_dpho = autoFunc_dJ_dpho(in1,in2,in3)
%AUTOFUNC_DJ_DPHO
%    DJ_DPHO = AUTOFUNC_DJ_DPHO(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    26-Sep-2021 22:55:02

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = cos(q1);
t3 = sin(q1);
t4 = q2+q3;
t5 = cos(t4);
t6 = sin(t4);
t7 = -t6;
t8 = t2.*t5;
t9 = t3.*t5;
t10 = t2.*t6;
t11 = t3.*t6;
t12 = -t8;
t13 = t2.*t7;
dJ_dpho = reshape([0.0,t10,t11,t7,t9,t12,t7,t9,t12,0.0,-t3,t2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t12,-t9,t5,t11,t13,t5,t11,t13],[9,3]);
