function out_dJ = dJb(q1,q2,q3,dq1,dq2,dq3)
%DJB
%    OUT_DJ = DJB(Q1,Q2,Q3,DQ1,DQ2,DQ3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    08-Jun-2021 20:24:55

t2 = cos(q1);
t3 = cos(q2);
t4 = sin(q1);
t5 = sin(q2);
t6 = dq2+dq3;
t7 = q2+q3;
t8 = dq2.*t3;
t9 = cos(t7);
t10 = sin(t7);
t11 = t3./5.0;
t12 = (dq2.*t5)./5.0;
t13 = t5+t10;
t14 = t9./5.0;
t15 = t6.*t9;
t16 = (t6.*t10)./5.0;
t17 = t8+t15;
t18 = t11+t14;
t19 = t12+t16;
out_dJ = reshape([0.0,dq1.*t2.*8.38e-2-t2.*t19-dq1.*t4.*t18,dq1.*t4.*8.38e-2-t4.*t19+dq1.*t2.*t18,t19,t4.*t17.*(-1.0./5.0)-(dq1.*t2.*t13)./5.0,(t2.*t17)./5.0-(dq1.*t4.*t13)./5.0,t16,t4.*t15.*(-1.0./5.0)-(dq1.*t2.*t10)./5.0,dq1.*t4.*t10.*(-1.0./5.0)+t2.*t6.*t14],[3,3]);
