function out_J = Jb(q1,q2,q3)
%JB
%    OUT_J = JB(Q1,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    08-Jun-2021 20:24:55

t2 = cos(q1);
t3 = cos(q2);
t4 = sin(q1);
t5 = sin(q2);
t6 = q2+q3;
t7 = cos(t6);
t8 = sin(t6);
t9 = t3./5.0;
t10 = t5+t8;
t11 = t7./5.0;
t12 = -t11;
t13 = t9+t11;
out_J = reshape([0.0,t4.*8.38e-2+t2.*t13,t2.*(-8.38e-2)+t4.*t13,-t9+t12,t4.*t10.*(-1.0./5.0),(t2.*t10)./5.0,t12,t4.*t8.*(-1.0./5.0),(t2.*t8)./5.0],[3,3]);
