//
// Academic License - for use in teaching, academic research, and meeting
// course requirements at degree granting institutions only.  Not for
// government, commercial, or other organizational use.
// File: autoFunc_dJ_drho.cpp
//
// MATLAB Coder version            : 5.2
// C/C++ source code generated on  : 08-Feb-2022 22:07:34
//

// Include Files
#include "autoFunc_dJ_drho.h"
#include <cmath>

// Function Definitions
//
// AUTOFUNC_DJ_DRHO
//     DJ_DRHO = AUTOFUNC_DJ_DRHO(IN1,LC,IN3)
//
// Arguments    : const double in1[3]
//                double lc
//                const double in3[4]
//                double dJ_drho[9]
// Return Type  : void
//
void autoFunc_dJ_drho(const double in1[3], double, const double[4],
                      double dJ_drho[9])
{
  double t10;
  double t5;
  double t6;
  double t7;
  double t8;
  //     This function was generated by the Symbolic Math Toolbox version 8.7.
  //     08-Feb-2022 22:07:24
  t5 = std::cos(in1[0]);
  t6 = std::sin(in1[0]);
  t7 = in1[1] + in1[2];
  t8 = std::cos(t7);
  t7 = std::sin(t7);
  t10 = t6 * t7;
  t7 *= t5;
  dJ_drho[0] = 0.0;
  dJ_drho[1] = t5 * t8;
  dJ_drho[2] = t6 * t8;
  dJ_drho[3] = -t8;
  dJ_drho[4] = -t10;
  dJ_drho[5] = t7;
  dJ_drho[6] = -t8;
  dJ_drho[7] = -t10;
  dJ_drho[8] = t7;
}

//
// File trailer for autoFunc_dJ_drho.cpp
//
// [EOF]
//
