function d_fk_ddrho = autoFunc_d_fk_ddrho(in1,lc,in3)
%autoFunc_d_fk_ddrho
%    D_FK_DDRHO = autoFunc_d_fk_ddrho(IN1,LC,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    18-May-2022 23:09:41

d_fk_ddrho = [0.0;0.0;0.0];
