figure(2)
matlab2tikz('vel_compare.tex',...
            'extraAxisOptions',{'ylabel near ticks','xlabel near ticks',...
            'scaled ticks=false',...
            'stack plots=false',...
            'legend style={at={(0.03,0.03)}, anchor=south west, legend cell align=left, align=left, draw=white!15!black},',...
            'xtick distance=0.5',...
            'ylabel shift = -25pt',...
            'xlabel shift = -10pt',...
%             'xtick={0,0.05,0.1}',...
%             'ytick distance=0.5',...
%             'minor tick num=1',...
%             'ylabel style={font=\small\fontfamily{ptm}\selectfont}',...
%             'xlabel style={font=\small\fontfamily{ptm}\selectfont}',...
%             'ticklabel style={font=\small\fontfamily{ptm}\selectfont}',...
            })