//
// Academic License - for use in teaching, academic research, and meeting
// course requirements at degree granting institutions only.  Not for
// government, commercial, or other organizational use.
// File: autoFunc_d_fk_ddrho.cpp
//
// MATLAB Coder version            : 5.2
// C/C++ source code generated on  : 08-Feb-2022 22:07:31
//

// Include Files
#include "autoFunc_d_fk_ddrho.h"

// Function Definitions
//
// AUTOFUNC_D_FK_DDRHO
//     D_FK_DDRHO = AUTOFUNC_D_FK_DDRHO(IN1,LC,IN3)
//
// Arguments    : const double in1[3]
//                double lc
//                const double in3[4]
//                double d_fk_ddrho[3]
// Return Type  : void
//
void autoFunc_d_fk_ddrho(const double[3], double, const double[4],
                         double d_fk_ddrho[3])
{
  //     This function was generated by the Symbolic Math Toolbox version 8.7.
  //     08-Feb-2022 22:07:24
  d_fk_ddrho[0] = 0.0;
  d_fk_ddrho[1] = 0.0;
  d_fk_ddrho[2] = 0.0;
}

//
// File trailer for autoFunc_d_fk_ddrho.cpp
//
// [EOF]
//
