//
// Academic License - for use in teaching, academic research, and meeting
// course requirements at degree granting institutions only.  Not for
// government, commercial, or other organizational use.
// File: autoFunc_dJ_dt.cpp
//
// MATLAB Coder version            : 5.2
// C/C++ source code generated on  : 17-Feb-2022 16:35:53
//

// Include Files
#include "autoFunc_dJ_dt.h"
#include <cmath>

// Function Definitions
//
// AUTOFUNC_DJ_DT
//     DJ_DQ = AUTOFUNC_DJ_DT(IN1,LC,IN3)
//
// Arguments    : const double in1[3]
//                double lc
//                const double in3[4]
//                double dJ_dq[27]
// Return Type  : void
//
void autoFunc_dJ_dt(const double in1[3], double lc, const double in3[4],
                    double dJ_dq[27])
{
  double dJ_dq_tmp;
  double t10;
  double t11;
  double t12;
  double t16;
  double t17;
  double t18;
  double t24;
  double t25;
  double t26;
  double t29;
  double t30;
  double t5;
  double t6;
  double t7;
  double t8;
  double t9;
  //     This function was generated by the Symbolic Math Toolbox version 8.7.
  //     17-Feb-2022 16:35:32
  t5 = std::cos(in1[0]);
  t6 = std::cos(in1[1]);
  t7 = std::cos(in1[2]);
  t8 = std::sin(in1[0]);
  t9 = std::sin(in1[1]);
  t10 = std::sin(in1[2]);
  t11 = in1[1] + in1[2];
  t12 = in3[3] * t6;
  t16 = lc * std::cos(t11);
  t17 = lc * std::sin(t11);
  t18 = t5 * t16;
  t25 = t12 + t16;
  t26 = in3[3] * t9 + t17;
  t11 = -(t8 * t16);
  t16 = -(t5 * t17);
  t24 = -(t8 * t17);
  t29 = -(t5 * t26);
  t30 = -(t8 * t26);
  dJ_dq[0] = 0.0;
  dJ_dq[1] =
      ((-in3[2] * t5 - t8 * t12) - lc * t6 * t7 * t8) + lc * t8 * t9 * t10;
  dJ_dq_tmp = lc * t5;
  dJ_dq[2] =
      ((-in3[2] * t8 + t5 * t12) + dJ_dq_tmp * t6 * t7) - dJ_dq_tmp * t9 * t10;
  dJ_dq[3] = 0.0;
  dJ_dq[4] = t29;
  dJ_dq[5] = t30;
  dJ_dq[6] = 0.0;
  dJ_dq[7] = t16;
  dJ_dq[8] = t24;
  dJ_dq[9] = 0.0;
  dJ_dq[10] = t29;
  dJ_dq[11] = t30;
  dJ_dq[12] = t26;
  dJ_dq[13] = -t8 * t25;
  dJ_dq[14] = t5 * t25;
  dJ_dq[15] = t17;
  dJ_dq[16] = t11;
  dJ_dq[17] = t18;
  dJ_dq[18] = 0.0;
  dJ_dq[19] = t16;
  dJ_dq[20] = t24;
  dJ_dq[21] = t17;
  dJ_dq[22] = t11;
  dJ_dq[23] = t18;
  dJ_dq[24] = t17;
  dJ_dq[25] = t11;
  dJ_dq[26] = t18;
}

//
// File trailer for autoFunc_dJ_dt.cpp
//
// [EOF]
//
